# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3

In [10]:
import numpy as np
np.arange(2,51,3)


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [18]:
list1 = []
list2 = []
for i in range(5):
    k = int(input("Enter elements of list1 "))
    list1.append(k)

for j in range(5):    
    l = int(input("Enter elements of list2 "))
    list2.append(l)
    
arr1 = np.array(list1)
arr2 = np.array(list2)

print(arr1)
print(arr2)
arr = np.concatenate((arr1,arr2))
print("Concatenated list",arr)

arr_sort1 = np.sort(arr1)
arr_sort2 = np.sort(arr2)
arr_sort = np.sort(arr)
print("Array after sorting")
print(arr_sort1)
print(arr_sort2)
print(arr_sort)    


Enter elements of list1 7
Enter elements of list1 8
Enter elements of list1 9
Enter elements of list1 4
Enter elements of list1 5
Enter elements of list2 6
Enter elements of list2 1
Enter elements of list2 2
Enter elements of list2 3
Enter elements of list2 8
[7 8 9 4 5]
[6 1 2 3 8]
Concatenated list [7 8 9 4 5 6 1 2 3 8]
Array after sorting
[4 5 7 8 9]
[1 2 3 6 8]
[1 2 3 4 5 6 7 8 8 9]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [19]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.ndim(array1)

2

In [26]:
array1.shape

(3, 3)

In [27]:
len(array1)

3

# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [28]:
print(np.arange(20))

[0 1 2 3 4 5 6 7 8 9]


In [31]:
matrix = np.arange(20).reshape(4,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
matrix.ndim

2

# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [34]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


# Questions 6:
How to get unique items and counts of unique items;

In [39]:
def unique(list1):
    x = np.array(list1)
    print(np.unique(x))
    
list1 = [1,8,8,2,4,2,9,6,4,9,9,1,8,6,4]
unique(list1)

count = set(list1)
print(len(count))

[1 2 4 6 8 9]
6
